pub const Error = error{
    PositionNull,
    MovesNull,
    OutOfBounds,
    NotInSameRow,
    CharInvalid,
    InvalidSquareRepresentation,
    InvalidInputLength,
    InvalidFenParts,
    InvalidBoardSetup,
    InvalidTurnCharacter,
    InvalidCastleInformation,
    InvalidEnPassantSquare,
    InvalidHalfMoveClock,
    InvalidFullMoveNumber,
};